name: ${name}
version: ${version}
author: ${author}
description: ${description}
website: ${homepage_url}
main: io.github.dexrnzacattack.rrdiscordbridge.FlatBukkitPlugin
commands:
  discord:
    description: Gives the discord invite link (if enabled)
    usage: /discord
  dcbroadcast:
    description: Broadcasts a message to the chat and Discord (but fancy)
    usage: /dcbroadcast <message>
    permission: dcbroadcast.use
    permission-message: Only people with dcbroadcast.use can use this command.
  reloadrdbconfig:
    description: Reloads the config (bukkit.reload sucks iirc)
    usage: /reloadrdbconfig
    permission: reloadrdbconfig.use
    permission-message: Only people with reloadrdbconfig.use can use this command.
  cext:
    description: Manage Chat Extensions from ingame, run /cext help for subcommands
    usage: /cext [subcmd] [options...]
    permission: cext.use
    permission-message: Only people with cext.use can use this command.
libraries:
  - net.dv8tion:JDA:5.2.1
  - club.minnced:discord-webhooks:0.8.4